[tool.uv.workspace]
members = [
    "apps/racing-api",
    "apps/racing-etl",
    "apps/trader",
    "libraries/api-helpers",
    "notebooks", 
    "matplotlib",
]

[tool.uv.sources]
api-helpers = { workspace = true }